name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-types:
    runs-on: ubuntu-latest
    name: Check types (node${{ matrix.node }})
    strategy:
      matrix: { node: [24] }
    steps:
      - &checkout
        uses: actions/checkout@v6
      - &setup-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - &setup-node
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node }}
      - run: pnpm install --frozen-lockfile
      - run: pnpm run typecheck
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 24]
    name: Run tests (node${{ matrix.node }})
    steps:
      - *checkout
      - *setup-pnpm
      - *setup-node
      - run: pnpm install --frozen-lockfile
      - run: pnpm test
