name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-types:
    runs-on: ubuntu-latest
    name: Check types
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - run: npm ci
      - run: npm run typecheck
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22]
    name: Run tests on Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test
